# Generated by Django 4.2.5 on 2023-09-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recursos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivo",
            name="archivo",
        ),
        migrations.AddField(
            model_name="archivo",
            name="archivos",
            field=models.FileField(blank=True, null=True, upload_to="archivos/"),
        ),
        migrations.CreateModel(
            name="ArchivoIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo_individual",
                    models.FileField(upload_to="archivos/individuales/"),
                ),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recursos.archivo",
                    ),
                ),
            ],
        ),
    ]
